// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

import MessageFormController from "./message-form_controller"
application.register("message-form", MessageFormController)

import ScrollToController from "./scroll-to_controller"
application.register("scroll-to", ScrollToController)

import AutoresizeController from "./autoresize_controller"
application.register("autoresize", AutoresizeController)

import HideController from "./hide_controller"
application.register("hide", HideController)
